# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7595d600774276fb81cdf5500cc35a296d613796aa33ba0ab525179cee2aeb436ae83483f4a155fd14e61232e117c6db18f799884993d0705152e7bb023eb9dc

test:
  secret_key_base: 65b084d31f3980781b184f1b6ccf569e66daa86d2fb994681f7b91f635d380e23d1648b60ef829e8ac050e5628722d00de59b5a2cdc16be54f2309fe69daa967

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
